### Cenário 1: Criar Ordem com Sucesso (Carga Otimizada)
POST http://localhost:8080/shipping-orders
Content-Type: application/json

{
  "vehicleId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 10,
      "customerName": "Importadora Pneus Brasil Ltda"
    },
    {
      "productId": 2,
      "quantity": 5,
      "customerName": "Borracharia São José"
    }
  ]
}

### Cenário 2: Estourar Limite de Cubagem/Peso (Carga Abusiva)
POST http://localhost:8080/shipping-orders
Content-Type: application/json

{
  "vehicleId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 5000,
      "customerName": "Distribuidora de Pneus Gigante"
    }
  ]
}

### Cenário 3: Testar Validação de Estoque Insuficiente (Estoque Esgotado)
POST http://localhost:8080/shipping-orders
Content-Type: application/json

{
  "vehicleId": 2,
  "items": [
    {
      "productId": 1,
      "quantity": 250,
      "customerName": "Atacadão de Pneus Auto"
    }
  ]
}