# Conexão com o Banco de Dados PostgreSQL (Porta padrão 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack_db
spring.datasource.username=postgres
spring.datasource.password=9430

# Mostra as instruções SQL geradas no console para fins de estudo e debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate ddl-auto: Faz o banco criar e atualizar as tabelas automaticamente baseado no código Java
spring.jpa.hibernate.ddl-auto=update

# Configura o dialeto específico do PostgreSQL para otimização de queries
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect